// Edit this file, then refresh the browser.
//
// A page is one block in the list below.
// 1. Put photos in images/<slug>/
// 2. Copy a city block. Set name, slug, lat, lng, label, and blurb.
//    label is where the name sits on the map: n, s, e, w, ne, nw, se, sw.
// 3. A section is a title and spots. A spot is words, plus a picture if you have one.
//    { name: "Place name", note: "short note", photo: "images/seattle/place.jpg" },
//    Leave photo off for words only. A section note sits above the spots.
//    lines: true puts each name and note on one line, like the NYC food list.
// A pin with no page is one line. Look up lat/lng, pick a label, refresh.
// { name: "Banff", lat: 51.18, lng: -115.57, label: "n" },

const cities = [
  {
    name: "Seattle",
    slug: "seattle",
    lat: 47.61,
    lng: -122.33,
    label: "nw",
    blurb: "I lived here for the summer in 2021 for an internship and most of these recs are from then. i've visited every year since then.",
    sections: [
      {
        title: "Places",
        spots: [
          { name: "Amazon Spheres", note: "need an Amazon employee to take you in", photo: "images/seattle/amazon-spheres.jpg" },
          { name: "Pike Place Market", photo: "images/seattle/pike-place.jpg" },
          { name: "Lake Union Park", photo: "images/seattle/lake-union-park.jpg" },
          { name: "UW", photo: "images/seattle/uw.jpg" },
          { name: "Gas Works Park", photo: "images/seattle/gas-works.jpg" },
          { name: "Kerry Park", photo: "images/seattle/kerry-park.jpg" },
          { name: "Arboretum / Japanese Garden", note: "across from each other, Bellevue Botanical Garden is better but further", photo: "images/seattle/arboretum.jpg" },
          { name: "Ravenna Park", note: "fav park in Seattle", photo: "images/seattle/ravenna-park.jpg" },
          { name: "Bainbridge Island", note: "nice views on the ferry, Mora's ice cream, take the ferry back at night", photo: "images/seattle/bainbridge.jpg" },
          { name: "Kinnear Park", note: "something to do in Queen Anne", photo: "images/seattle/kinnear-park.jpg" },
          { name: "Seward Park", note: "360 water views and nature trails, kinda far", photo: "images/seattle/seward-park.jpg" },
        ],
      },
      {
        title: "Food",
        spots: [
          { name: "Malatang", note: "hot pot", photo: "images/seattle/malatang.jpg" },
          { name: "Chi Mac", photo: "images/seattle/chi-mac.jpg" },
          { name: "The Alley", photo: "images/seattle/the-alley.jpg" },
          { name: "Molly Moon's", note: "ice cream flight", photo: "images/seattle/molly-moons.jpg" },
          { name: "Seattle's Best Tea", note: "heavy oolong tea with lychee jelly", photo: "images/seattle/seattles-best-tea.jpg" },
          { name: "Piroshky Piroshky", photo: "images/seattle/piroshky.jpg" },
          { name: "GH Pasta Co", note: "chili flakes with the pasta", photo: "images/seattle/gh-pasta.jpg" },
          { name: "Cafe on the Ave", photo: "images/seattle/cafe-on-the-ave.jpg" },
          { name: "Bangrak Market", note: "looks like a street market inside", photo: "images/seattle/bangrak.jpg" },
          { name: "Post Alley Pizza", note: "pepperoni with hot honey", photo: "images/seattle/post-alley-pizza.jpg" },
          { name: "Dough Zone", note: "cheap din tai fung, Yelp waitlist before" },
          { name: "Xi'an Noodles" },
          { name: "Bongos", note: "next to Green Lake Park" },
          { name: "Korean Bamboo" },
        ],
      },
      {
        title: "Things to do",
        spots: [
          { name: "Paddle boarding on Lake Union", note: "better than kayaking", photo: "images/seattle/paddle-boarding.jpg" },
          { name: "Bars in Capitol Hill", note: "the M" },
          { name: "Bus to Bellevue" },
          { name: "Hike at Mt. Rainier" },
          { name: "Markets", note: "Fremont flea market, Ballard farmers market" },
          { name: "Electric scooters by the piers at night" },
        ],
      },
    ],
  },
  {
    name: "Chicago",
    slug: "chicago",
    lat: 41.88,
    lng: -87.63,
    label: "n",
    blurb: "I stayed in Chicago for 2 weeks in 2023 in Michelle's apartment and another 2 weeks in 2025. Most of these recommendations came from Michelle, who lived there for 3 years.",
    sections: [
      {
        title: "Places",
        spots: [
          { name: "Millennium Park", note: "the Bean, walk around and take pictures", photo: "images/chicago/millennium-park.jpg" },
          { name: "Navy Pier", note: "walk around and take pictures, pretty skyline" },
          { name: "Lakefront Trail", note: "walk, bike, or run, jump in the lake if it's nice, and there are beaches to sit at in summer and fall" },
          { name: "Garfield Park Conservatory", note: "free, reserve ahead", photo: "images/chicago/garfield-conservatory.jpg" },
          { name: "Lincoln Park Zoo", note: "My favorite spot in Chicago! It's a free park and you can just sit and read then walk around and look at animals. I think I went a total of 3 times.", photo: "images/chicago/lincoln-park-zoo.jpg" },
          { name: "Riverwalk", note: "cafes, bars, and shops along the river, Tiny Tap is an easy place to sit", photo: "images/chicago/riverwalk.jpg" },
        ],
      },
      {
        title: "Museum Campus",
        spots: [
          { name: "Shedd Aquarium", note: "on the campus with the Field Museum", photo: "images/chicago/shedd-aquarium.jpg" },
          { name: "Field Museum", photo: "images/chicago/field-museum.jpg" },
          { name: "Art Institute", note: "by Millennium Park, a short walk from the campus", photo: "images/chicago/art-institute.jpg" },
        ],
      },
      {
        title: "Food",
        spots: [
          { name: "Ema", note: "Mediterranean, make a reservation, I liked it more than Aba and it's the best food I had in Chicago", photo: "images/chicago/ema.jpg" },
          { name: "Pequod's", note: "deep dish, worth the trek, Lou Malnati's is the downtown one if you want it convenient", photo: "images/chicago/deep-dish.jpg" },
          { name: "Chicago dog", note: "Portillo's or Devil Dawgs, or The Wieners Circle if you want them to yell at you" },
          { name: "Au Cheval", note: "a really good burger, I got it to go twice because a table is hard to get, Michelle thinks it's a bit overrated, Small Cheval is less upscale with a shorter wait", photo: "images/chicago/au-cheval.jpg" },
          { name: "Green Street Smoked Meats", note: "meat by the pound, the cornbread is good" },
          { name: "Kasama", note: "Filipino, Michelin star, the dinner tasting menu is ridiculously expensive, brunch is reasonable but not that impressive, the pastries are really good and the wait is long" },
          { name: "Robert's Pizza", note: "a top 5 pizza" },
          { name: "Momotaro", note: "a bit more upscale" },
          { name: "Bavette's", note: "Michelle's favorite steak, Armitage Ale House is the pot pie spot from the same group, hard to book but two people at opening can usually walk in" },
          { name: "Monteverde", note: "upscale Italian" },
          { name: "Prime & Provisions", note: "happy hour was $1 oysters, not sure they still have it" },
          { name: "Volumes Book Cafe", note: "hot matcha latte, the vibes are cute" },
        ],
      },
      {
        title: "Things to do",
        spots: [
          { name: "Architecture boat tour", photo: "images/chicago/architecture-boat.jpg" },
          { name: "Sluggers", note: "batting cages in a bar" },
          { name: "Tin Lizzie's", note: "all you can drink and all you can eat pizza, the food and drinks are whatever but the turtle races are fun" },
          { name: "The Infinite Wrench", note: "short plays" },
          { name: "Green Mill", note: "$20 cover, cash only", photo: "images/chicago/green-mill.jpg" },
          { name: "Where to stay", note: "near a train in River North, Streeterville, the Loop, Old Town, Gold Coast, or Wicker Park, the Loop is easiest since every train connects there" },
        ],
      },
    ],
  },
  { name: "Puerto Vallarta", lat: 20.65, lng: -105.23, label: "w" },
  {
    name: "NYC",
    slug: "nyc",
    lat: 40.71,
    lng: -74.01,
    label: "e",
    blurb: "Lived here for the summer of 2024 and 2026, but have been visiting at least twice a year ever since my sister started living here in 2021. Take the subway and walk! Don't take an Uber even to the airport.",
    sections: [
      {
        title: "Places",
        spots: [
          { name: "Riverside Park", note: "My favorite park in the entire world. Sit on a bench and read, or eat banh mi from Saiguette. In the fall, and watching kids play after school, peak happiness.", photo: "images/nyc/riverside-park.jpg" },
          { name: "Central Park", note: "Bike the 6 mile loop or walk around Belvedere Castle, Bow Bridge, or the Great Lawn. SummerStage and Shakespeare in the Park during the summer.", photo: "images/nyc/central-park.jpg" },
          { name: "Bryant Park", note: "Christmas markets or summer movie nights.", photo: "images/nyc/bryant-park.jpg" },
          { name: "High Line", note: "Chelsea Market, the High Line, and Little Island. I recommend biking the West Side Highway too. The High Line was our afternoon walk.", photo: "images/nyc/high-line.jpg" },
          { name: "New York Botanical Garden", note: "Best to go in the spring. Next to the zoo, which I liked as well.", photo: "images/nyc/botanical-garden.jpg" },
          { name: "Empire State Building", note: "I can take you up for free, so don't go yourself. Summit One is much better and you get a view of the Empire State Building.", photo: "images/nyc/empire-state.jpg" },
          { name: "Governors Island", note: "No one talks about this place but I love it. Take a ferry, only a 5 minute ride, and get a close view of the Statue of Liberty. There's Citi Bike, so I bike the perimeter in an hour. There's an art walk and hammocks too.", photo: "images/nyc/governors-island.jpg" },
          { name: "Brooklyn Bridge Park", note: "And walk the Brooklyn Bridge.", photo: "images/nyc/brooklyn-bridge.jpg" },
          { name: "Roosevelt Island", note: "Take the tram. Views of the city on a nice day. We also went in winter and it was miserable.", photo: "images/nyc/roosevelt-island.jpg" },
          { name: "Brooklyn Botanic Garden", note: "Highly recommend the Christmas light show.", photo: "images/nyc/brooklyn-botanical.jpg" },
          { name: "The Strand", note: "The bookstore that got me into reading. Huge, then read in Washington Square Park afterwards.", photo: "images/nyc/the-strand.jpg" },
          { name: "Biddy's", note: "I suck at trivia, so I play bingo on Wednesday nights instead.", photo: "images/nyc/biddys.jpg" },
        ],
      },
      {
        title: "Museums",
        spots: [
          { name: "The Met", note: "Allocate at least 3 hours, and don't skip the Impressionism section.", photo: "images/nyc/the-met.jpg" },
          { name: "The Met Cloisters", note: "About an hour by subway and bus, but so worth it for the architecture.", photo: "images/nyc/met-cloisters.jpg" },
          { name: "The Frick", note: "Free first Fridays. A taste of how rich people are on the Upper East Side.", photo: "images/nyc/the-frick.jpg" },
          { name: "The Morgan Library", photo: "images/nyc/morgan-library.jpg" },
          { name: "Guggenheim", note: "Only go if the exhibit is good. The spiral is nice, but that's about it, since it's all modern art.", photo: "images/nyc/guggenheim.jpg" },
          { name: "American Museum of Natural History", note: "Fun if you're already in the area. The lobby is where everyone takes pictures, so you don't even need to go in, though I would, it's fun.", photo: "images/nyc/natural-history.jpg" },
          { name: "Noguchi Museum", note: "All about his sculptures, not lanterns. Go when there's a tour.", photo: "images/nyc/noguchi.jpg" },
        ],
      },
      {
        title: "Broadway",
        spots: [
          { name: "Wicked", note: "The definition of a Broadway musical, don't skip." },
          { name: "Book of Mormon", note: "Catchy songs and so funny." },
          { name: "Hamilton", note: "Exactly like the Disney Plus version, so only pay if you're a super fan, which I am, because tickets are $200+.", photo: "images/nyc/hamilton.jpg" },
        ],
      },
      {
        title: "Events",
        spots: [
          { name: "NYC Ballet", note: "30 under 30.", photo: "images/nyc/nyc-ballet.jpg" },
          { name: "Coney Island", note: "Free fireworks every Friday in summer. The closest I've been to fireworks, and the boardwalk. We rode the Thunderbolt.", photo: "images/nyc/coney-island.jpg" },
          { name: "US Open", note: "Fan week, free tickets to the qualifying rounds. Our favorite event of the summer.", photo: "images/nyc/us-open.jpg" },
          { name: "concert at MSG" },
          { name: "Yankees", note: "The subway goes right there." },
          { name: "Mets", note: "We went later in the season when they were already out of the playoffs and had a $10 food voucher. Tickets were $16.", photo: "images/nyc/mets.jpg" },
          { name: "Sleep No More", note: "The most insane experience. An interactive show where you chase the actors and no one talks, in an abandoned hotel. They're closed now, but hopefully they come back.", photo: "images/nyc/sleep-no-more.jpg" },
        ],
      },
      {
        title: "Food",
        note: "full food ranking and pictures on my beli: https://beliapp.co/app/kerrizhang",
        lines: true,
        spots: [
          { name: "pizza", note: "lucia pizza but everyone loves lindustrie" },
          { name: "bagel", note: "popup bagels but justin likes apollo more" },
          { name: "korean", note: "olle, andamiro" },
          { name: "thai", note: "fish cheeks" },
          { name: "chinese", note: "nai brother LiC, 1915 lanzhou, laoma spicy" },
          { name: "japanese", note: "toribro ramen, konban" },
          { name: "italian", note: "san sabino" },
          { name: "halal", note: "adels or shwarma bay" },
          { name: "indian", note: "semma" },
          { name: "mexican", note: "rey de reyes, los tacos no 1" },
          { name: "bar", note: "tomi jazz" },
          { name: "dessert", note: "myka" },
        ],
      },
      {
        title: "Day trips",
        spots: [
          { name: "Cold Spring", note: "Cute town from the train station, and a tough hike.", photo: "images/nyc/cold-spring.jpg" },
          { name: "New Canaan", note: "Grace Farms.", photo: "images/nyc/grace-farms.jpg" },
          { name: "New Haven", note: "Frank Pepe pizza and Yale, the rare book library.", photo: "images/nyc/new-haven.jpg" },
          { name: "Untermyer Gardens", note: "A rich guy's private garden, now free. About 1.5 hours by train and walking from the city.", photo: "images/nyc/untermyer.jpg" },
          { name: "Wave Hill", note: "A nature oasis on the Hudson. There's a free shuttle from the train station.", photo: "images/nyc/wave-hill.jpg" },
          { name: "Where to stay", note: "NYC doesn't allow Airbnbs. Find a hotel in Soho, all roads lead back to Soho, or anywhere close to a subway. Don't stay in Times Square or Harlem." },
        ],
      },
    ],
  },
  { name: "SF", lat: 37.77, lng: -122.42, label: "w" },
  { name: "South America", lat: -15.6, lng: -58.2, label: "e" },
  { name: "Mexico City", lat: 19.43, lng: -99.13, label: "e" },
  { name: "London", lat: 51.51, lng: -0.13, label: "ne" },
  { name: "Irvine", lat: 33.67, lng: -117.83, label: "sw" },
  { name: "South of France", lat: 42.6, lng: 3.7, label: "sw" },
  { name: "Banff", lat: 51.18, lng: -115.57, label: "n" },
  { name: "Scotland", lat: 56.49, lng: -4.2, label: "nw" },
  { name: "Japan", lat: 36.2, lng: 138.25, label: "e" },
  { name: "Korea", lat: 37.57, lng: 126.98, label: "w" },
  { name: "Beijing", lat: 39.9, lng: 116.41, label: "n" },
  { name: "Norway", lat: 60.47, lng: 8.47, label: "w" },
  { name: "Sweden", lat: 59.33, lng: 18.07, label: "e" },
  { name: "Switzerland", lat: 46.8, lng: 8.23, label: "ne" },
  { name: "Denmark", lat: 55.68, lng: 12.57, label: "s" },
  { name: "Easter Island", lat: -27.11, lng: -109.35, label: "e" },
  // Spread a little so both pins show. True centers: Maui 20.80, -156.33 and Oahu 21.44, -157.86.
  { name: "Maui", lat: 20.0, lng: -154.3, label: "se" },
  { name: "Oahu", lat: 22.3, lng: -160.0, label: "nw" },
];
